Some minor changes to easy implementation on top of kontiki
NicolasT/kontiki pull request #20
Opened 2016-01-05 13:36 UTC by abailly

This PR contains a bunch of changes I had to make to kontiki in order to implement [raptr](https://github.com/capital-match/raptr):

* reset timeouts even when they are ignored by current state
* store last known leader within follower's state

I also moved tests to more standard test/ directory and reorganized them to use tasty. 

I can split this PR in smaller chunks if required.

2017-01-12 23:45 UTC, NicolasT commented
I'm sorry I completely missed this PR (and it's been  a year... :-/)
I'll go over it right away.

2017-01-13 00:01 UTC, NicolasT requested changes
Several questions, and some things I think definitely need to change:
- Don't only support AMP compilers, ideally
- Don't expose MemLog
- Keep dependency version bounds

2017-01-13 00:01 UTC, NicolasT commented on bin/demo.hs
> +import           Data.Kontiki.MemLog
See later comment

2017-01-13 00:01 UTC, NicolasT commented on kontiki.cabal
> +                     , Data.Kontiki.MemLog
I'm not very fond of this. The `MemLog` implementation is something that can be useful in tests, and may be useful in some demo tools, but it defies all guarantees a system like Raft needs from its log implementation w.r.t. (crash) safety.

As such, I don't think this module should be part of the library and definitely not be exposed as part of its API to any users.

2017-01-13 00:01 UTC, NicolasT commented on kontiki.cabal
> +  Build-Depends:       base
I really like to have version bounds in dependency definitions. The bounds may be too restrictive (the code is getting quite old...), but just dropping them makes publishing this package to Hackage or usage by others more difficult.

2017-01-13 00:01 UTC, NicolasT commented on kontiki.cabal
> +                     , test-framework
Is `test-framework` etc still used given your changes?

2017-01-13 00:01 UTC, NicolasT commented on src/Data/Kontiki/MemLog.hs
> +import           Data.IntMap          (IntMap)
Des gouts et des couleurs... but I don't like this formatting ;)

2017-01-13 00:01 UTC, NicolasT commented on src/Network/Kontiki/Raft.hs
> +handle :: (Monad m, MonadLog m a)
This removes compatibility with older compilers. The 'Redundant Constraints' warning of GHC8.0.1 was basically a mistake and is (for good reason) being removed from `-Werror` again, if I'm not mistaken (check GHC Trac). Would it be possible to add `-fno-warn-redundant-constraints` to the GHC options in the Cabal file instead (under a version check)?

2017-01-13 00:01 UTC, NicolasT commented on src/Network/Kontiki/Raft/Candidate.hs
> +    resetHeartbeatTimeout
Are you sure this is the correct thing to do? We don't have to send a heartbeat as long as we're Candidate, so why resetting its timeout?

2017-01-13 00:01 UTC, NicolasT commented on src/Network/Kontiki/Raft/Follower.hs
> +    resetHeartbeatTimeout
Same question as for the change in Candidate.

2017-01-13 00:01 UTC, NicolasT commented on src/Network/Kontiki/Raft/Leader.hs
> +  resetElectionTimeout
Similar question as the similar heartbeat timeout change in Candidate or Follower state

2017-01-13 00:01 UTC, NicolasT commented on src/Network/Kontiki/Raft/Utils.hs
> +{-# LANGUAGE FlexibleContexts, OverloadedStrings, ScopedTypeVariables, TypeFamilies #-}
This is a different formatting than the other changes.

2017-01-13 00:01 UTC, NicolasT commented on src/Network/Kontiki/Raft/Utils.hs
> +        MRequestVote m'           -> handleRequestVote s m'
Hmpf.

2017-01-13 00:01 UTC, NicolasT commented on test/Network/Kontiki/RaftSpec.hs
> +module Network.Kontiki.RaftSpec where
I'm very confused by this module in general. What is it testing? Why is Test.QuickCheck, MemLog,... imported?

2017-01-13 00:01 UTC, NicolasT commented on test/kontiki-test.hs
> +{-# LANGUAGE FlexibleInstances          #-}
Since all tests use HSpec, any reason to use Tasty at all?

2017-01-13 01:09 UTC, abailly commented
Thanks for the comments, I will address them.

2017-07-29 16:07 UTC, closed without merging